backend:
  name: git-gateway
  branch: main
media_folder: "public/images/uploads"
public_folder: "images/uploads"
collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home"
        file: "_org/home.yml"
        fields:
          - name: "background"
            label: "Hero Image"
            widget: "image"
            allow_multiple: false
          - name: "head"
            label: "Hero Header"
            widget: "string"
          - name: "body"
            label: "Hero Body"
            widget: "text"
      - name: "profile"
        label: "Profile"
        file: "_org/profile.yml"
        fields:
          - name: "identity"
            label: "Identity"
            widget: "text"
          - name: "vision"
            label: "Vision"
            widget: "text"
          - name: "mission"
            label: "Mission"
            widget: "text"
      - name: "contact"
        label: "Contact"
        file: "_org/contact.yml"
        fields:
          - name: "twitter"
            label: "Twitter"
            widget: "string"
          - name: "instagram"
            label: "Instagram"
            widget: "string"
          - name: "youtube"
            label: "Youtube"
            widget: "string"
          - name: "number"
            label: "Contact Number"
            widget: "string"
          - name: "email"
            label: "E-Mail Address"
            widget: "string"
          - name: "line"
            label: "Line"
            widget: "string"
          - name: "address"
            label: "Address"
            widget: "string"
  - name: "division"
    label: "Division"
    folder: "_org/division"
    identifier_field: "name"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "name"
        label: "Name"
        widget: "string"
      - name: "logo"
        label: "Logo"
        widget: "image"
        allow_multiple: false
      - name: "description"
        label: "Description"
        widget: "text"
  - name: "member"
    label: "Member"
    folder: "_org/member"
    identifier_field: "name"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "name"
        label: "Name"
        widget: "string"
      - name: "gen"
        label: "Year of Graduation"
        widget: "number"
      - name: "division"
        label: "Division"
        widget: "relation"
        collection: "division"
        value_field: "name"
        search_fields: ["name"]
        display_fields: ["name"]
      - name: "occupation"
        label: "Current Occupation"
        widget: "string"
      - name: "message"
        label: "Message"
        widget: "text"
        required: false
  - name: "blog"
    label: "Blog"
    folder: "_posts/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "author"
        label: "Author"
        widget: "relation"
        collection: "member"
        value_field: "name"
        search_fields: ["name", "gen"]
        display_fields: ["name", "gen"]
      - name: "cover"
        label: "Cover Image"
        widget: "image"
        allow_multiple: false
      - name: "body"
        label: "Body"
        widget: "markdown"
      - name: "date"
        label: "Publish Date"
        widget: "datetime"
  - name: "event"
    label: "Event"
    folder: "_posts/event"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "cover"
        label: "Cover Image"
        widget: "image"
        allow_multiple: false
      - name: "address"
        label: "Address"
        widget: "string"
      - name: "date"
        label: "Date"
        widget: "object"
        fields:
          - name: "start"
            label: "Start"
            widget: "datetime"
          - name: "end"
            label: "End"
            widget: "datetime"
      - name: "body"
        label: "Body"
        widget: "markdown"